let cities = [
'Delhi',
'Mumbai',
'Kolkata',
'Chennai',
'Bengaluru',
'Hyderabad',
'Ahmedabad',
'Pune',
'Jaipur',
'Lucknow',
'Kanpur',
'Nagpur',
'Indore',
'Bhopal',
'Patna',
'Ranchi',
'Raipur',
'Bhubaneswar',
'Chandigarh',
'Dehradun',
'Guwahati',
'Imphal',
'Shillong',
'Aizawl',
'Kohima',
'Agartala',
'Gangtok',
'Itanagar',
'Panaji',
'Thiruvananthapuram',
'Kochi',
'Madurai',
'Coimbatore',
'Visakhapatnam',
'Vijayawada',
'Warangal',
'Nashik',
'Vadodara',
'Surat',
'Rajkot',
'Jodhpur',
'Udaipur',
'Meerut',
'Varanasi',
'Prayagraj',
'Gorakhpur',
'Bareilly',
'Moradabad',
'Agra',
'Noida',
'Ghaziabad',
'Faridabad',
'Gurugram',
'Jamshedpur',
'Dhanbad',
'Bilaspur',
'Jorhat',
'Dibrugarh',
'Siliguri',
'Howrah',
'Asansol',
'Darjeeling',
'Ajmer',
'Aligarh',
'Amritsar',
'Ludhiana',
'Jalandhar',
'Hisar',
'Rohtak',
'Panipat',
'Karnal',
'Haldwani',
'Nainital',
'Shimla',
'Kullu',
'Manali',
'Srinagar',
'Jammu',
'Leh',
'Gwalior',
'Jabalpur',
'Rewa',
'Satna',
'Sagar',
'Kolhapur',
'Solapur',
'Aurangabad',
'Amravati',
'Chandrapur',
'Akola',
'Nanded',
'Parbhani',
'Thrissur',
'Calicut',
'Alappuzha',
'Kollam',
'Tirunelveli',
'Tiruppur',
'Salem',
'Trichy',
'Thoothukudi',
'Nellore',
'Kurnool',
'Anantapur',
'Kadapa',
'Eluru',
'Belgaum',
'Hubbali',
'Mangaluru',
'Mysuru',
'Shimoga',
'Davanagere',
'Ballari',
'Bagalkot',
'Sambalpur',
'Rourkela',
'Balasore',
'Cuttack',
'Durgapur',
'Bardhaman',
'Malda',
'Kharagpur',
'Tezpur',
'Tinsukia',
'Nagaon',
'Dimapur',
'Ambala',
'Yamunanagar',
'Kurukshetra',
'Muzaffarpur',
'Bhagalpur',
'Gaya',
'Katihar',
'Begusarai',
  "Ayodhya", "Mathura", "Saharanpur", "Firozabad", "Faizabad",
    "Navi Mumbai", "Amravati", "Kalyan-Dombivli", "Ulhasnagar", "Sangli",
    "Bhavnagar", "Jamnagar", "Gandhinagar", "Anand", "Bhuj",
    "Bikaner", "Kota", "Sikar", "Bharatpur", "Alwar",
    "Tiruchirappalli", "Erode", "Vellore", "Tiruvannamalai", "Kanchipuram",
    "Belagavi", "Tumakuru", "Udupi", "Hassan", "Chikmagalur",
    "Tirupati", "Guntur", "Ongole", "Rajahmundry", "Kakinada",
    "Nizamabad", "Karimnagar", "Khammam", "Mahbubnagar", "Nalgonda",
    "Kottayam", "Kannur", "Palakkad", "Pathanamthitta", "Idukki",
    "Bathinda", "Patiala", "Mohali", "Moga", "Firozpur",
    "Panchkula", "Sirsa", "Yamunanagar", "Kurukshetra", "Kaithal",
    "Ujjain", "Ratlam", "Dewas", "Chhindwara", "Satna",
    "Darbhanga", "Purnia", "Arrah", "Chapra", "Gopalganj",
    "Durgapur", "Kharagpur", "Haldia", "Malda", "Krishnanagar",
    "Cuttack", "Sambalpur", "Balasore", "Berhampur", "Rourkela",
    "Bokaro Steel City", "Hazaribagh", "Giridih", "Deoghar", "Ramgarh",
    "Bilaspur", "Korba", "Durg", "Jagdalpur", "Ambikapur",
    "Haridwar", "Rudrapur", "Kashipur", "Roorkee", "Pithoragarh",
    "Dharamshala", "Solan", "Mandi", "Bilaspur", "Una",
    "Anantnag", "Baramulla", "Kupwara", "Pulwama", "Kathua",
    "Silchar", "Nagaon", "Tezpur", "Dibrugarh", "Tinsukia",
    "Udaipur", "Dharmanagar", "Kailasahar", "Belonia", "Khowai",
    "Tura", "Nongpoh", "Jowai", "Baghmara", "Williamnagar",
    "Thoubal", "Bishnupur", "Churachandpur", "Ukhrul", "Senapati",
    "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Phek",
    "Lunglei", "Champhai", "Serchhip", "Kolasib", "Saiha",
    "Tawang", "Ziro", "Pasighat", "Bomdila", "Roing",

];

const resultsBox = document.querySelector(".result-box");
const inputBox = document.querySelector("#cityInput");

inputBox.onkeyup = function(){
    let result = [];
    let input = inputBox.value;
    if(input.length){
        result = cities.filter((keyword)=>{
          return  keyword.toLowerCase().includes(input.toLowerCase());
        });
        console.log(result);
    }
    display(result);
    if(!result.length){
        resultsBox.innerHTML = '';
    }
}
function display(result){
    const content = result.map((list)=>{
        return "<li onclick=selectInput(this)>" + list +"</li>";
    });
    resultsBox.innerHTML = "<ul>"+ content.join('')+"</ul>";
}
function selectInput(list) {
    inputBox.value = list.innerHTML;
    resultsBox.innerHTML = '';
}
